<!DOCTYPE html>
<html>
<head>
<title>Resume Submitted</title>
</head>
<body>
	<p>Hello ${fullName!''}</p>
	<p>A candidate has applied for the position of ${jobPosition}. Please interview the candidate and the interview has been scheduled at ${interviewTime}.</p>
	<br />
	<p>Candidate Profile: </p>${profile}
	<br />
	<p>Interview Information:</p>
	${description}
	<br />
	<p>Thanks</p>


</body>
</html>
