<!DOCTYPE html>
<html>
<head>
<title>Forgot Password - Reset Process</title>
</head>
<body>
	<h3>Hello ${fullName!''}</h3>

	<p>This is a verification for password reset email .</p>

    <p>Seems like you have requested for password reset in our system <p>

    <h4>CLick the reset link below, to change your password. <h4>

    <p><strong> Link: <br> </strong>${linkForgotPasswordReset}</p>

    <br>
    <p>If this wasn't you, please simply ignore this email. </p>

</body>
</html>
